### ISSUE TITLE
MAC address not read from EEPROM or AM335X registers

### ISSUE THREAD

**Issue by CaptChrisD** [nerves-project/nerves_system_bbb#111]
### Environment

* Elixir version (`elixir -v`):

```
$ elixir -v
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```

* Nerves environment: (`mix nerves.env --info`)
```
$ mix nerves.env --info
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        /Users/chris/code/nerves/hello_world

|nerves_bootstrap| Loadpaths End
```

```
$ MIX_TARGET=bbb mix nerves.env --info
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_bbb
  Vsn:         2.3.1
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_system_br
  Vsn:         1.8.4
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.2.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.6.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     bbb
  toolchain:  /Users/chris/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-1.2.0
  system:     /Users/chris/.nerves/artifacts/nerves_system_bbb-portable-2.3.1
  app:        /Users/chris/code/nerves/hello_world

|nerves_bootstrap| Loadpaths End
```
* Additional information about your host, target hardware or environment that
  may help

Targeting `BBB` with the latest nerves package and latest `nerves_system_bbb` with Elixir 1.9 and OTP 22. But this issue seemed to be present before upgrading as well.

### Current behavior

Include errors, stacktraces, screenshots or code that may help us reproduce the
issue.

Repro:
1) Create brand new project targeting BBB `mix nerves.new hello_world --target=bbb`
2) Build the projects `MIX_TARGET=bbb mix deps.get` `MIX_TARGET=bbb mix firmware.burn`
3) Boot device and check MAC address used `iex> ifconfig` ->
```
iex(3)> ifconfig
lo: flags=[:up, :loopback, :running]
    inet 127.0.0.1  netmask 255.0.0.0
    inet ::1  netmask ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    hwaddr 00:00:00:00:00:00

eth0: flags=[:broadcast, :multicast]
    hwaddr 78:00:00:00:00:00

usb0: flags=[:up, :broadcast, :running, :multicast]
    inet 172.31.105.165  netmask 255.255.255.252  broadcast 172.31.105.167
    inet fe80::38e1:74ff:fe38:b4a3  netmask ffff:ffff:ffff:ffff::
    hwaddr 3a:e1:74:38:b4:a3
```

I have tried this on 3 boards now (2 BBB and 1 Octavo based board) all with the same results

### Expected behavior

The MAC address should be read from either the EEPROM or the AM335X registers.

### Note
I am more than happy to look into this, but if someone could help point me in the correct direction. I am trying to upgrade from VERY old tooling and this is a major block for me at the moment.

**Comment by fhunleth** [comment]
Confirmed.

It works on my BBB-derived board so at some point I fixed it. The place to look is U-Boot and probably for things with the name "cpsw" in it. In my quick look, I'm mostly seeing stuff that doesn't make sense with setting the U-Boot environment with MAC addresses rather than getting values from the E-Fuses. I assume that mainstream BBB wants to be able to force MAC addresses or something. I'm timing out for now, though.
