### ISSUE TITLE
Beagle Bone Green Wireless does not connect to Wifi using onboard Wifi module

### ISSUE THREAD

**Issue by brucepom** [nerves-project/nerves_system_bbb#12]
I took the following steps:
- Use the latest BBB system
- Create a nerves app and add InterimWifi as a dependancy
- Burn firmware and insert SD in a BBGW
- Attempt to connect the BBGW to my Wifi network by running the following:
```
:os.cmd('modprobe wl18xx')
{ok, pid} = Nerves.InterimWiFi.setup "wlan0", ssid: "xxx", key_mgmt: :"WPA-PSK", psk: "yyy"
```
I get no error messages, but I don't think I'm actually successfully connecting to my wlan.

After calling `Nerves.InterimWiFi.setup` I get some output which ends with `[info]  Done Registering`) but that's all I get, I'd expect to get a lot more output from InterimWifi and probably expect to see something like `WiFiManager.EventHandler(wlan0) wifi_connected` if it had actually connected. I tried a couple of other things to see if I had a network connection:
Check if interface exists:
```
iex(4)> Nerves.NetworkInterface.interfaces
["lo"] # Note no wlan0 listed
```

Check for internet connectivity:

```
iex(5)> :httpc.request(:get, {'http://www.erlang.org', []}, [], [])
{:error,
 {:failed_connect,
  [{:to_address, {'www.erlang.org', 80}}, {:inet, [:inet], :nxdomain}]}}
```

I've been able to connect to the internet by following the same basic procedure on a LinkIt so I think I have my wifi details correct.

Thanks!

**Comment by fhunleth** [comment]
I'm not sure if you're using an officially released system or building a system using the `master` branch. If you're using the officially released system, then this is expected since a release hasn't been made yet with BBGW support. If you're building from master, maybe @cblock can help since he got it working at https://github.com/nerves-project/nerves_system_bbb/issues/8#issuecomment-288822473.

**Comment by brucepom** [comment]
Thanks @fhunleth I may have created some confusion by opening a new ticket for this. If you check out the last two comments on https://github.com/nerves-project/nerves_system_bbb/issues/8. It looks like although @cblock got the driver working he wasn't able to make a connection to his wifi network. Sorry for the confusion, I'm not sure if this is best tracked as a new issue or if we should keep the discussion in https://github.com/nerves-project/nerves_system_bbb/issues/8.

**Comment by cblock** [comment]
Hi @brucepom. That's right. I'm now trying to use `nerves_wpa_supplicant`directly in order to get closer to error messages. But so far with little success. Maybe @fhunleth is there a way to escape from iex and switch into a regular shell?

**Comment by fhunleth** [comment]
Ok, I think that I understand now.

@cblock There are two ways to get to a regular shell. One is to type
 `<Ctrl+G>s 'Elixir.Nerves.Runtime.Shell'<Enter>c<Enter>`. This will keep the Erlang VM up and let you type commands. Ctrl+C still exits the Erlang VM, so you have to be a little careful with it. The other option is to override the default `erlinit.conf` and uncomment this line: https://github.com/nerves-project/nerves_system_bbb/blob/master/rootfs-additions/etc/erlinit.config#L25. You can do that in your project's rootfs-additions. Then if you CTRL+C, CTRL+C, you'll exit the Erlang VM and enter a shell.

**Comment by cblock** [comment]
So I tried to compare the `linux-4.4.43.defconfig` in this repository with the one at https://github.com/beagleboard/linux
One thing I found to be notably differnet are the  CONFIG_WL* entries.

`linux-4.4.43.defconfig` in this repo:
```
CONFIG_WL_TI=y
CONFIG_WL18XX=m
```
[`bb.org_defconfig`](https://github.com/beagleboard/linux/blob/4.4/arch/arm/configs/bb.org_defconfig#L870) in beagleboard repo:
```
CONFIG_WL_TI=y
CONFIG_WL1251=m
CONFIG_WL1251_SPI=m
CONFIG_WL1251_SDIO=m
CONFIG_WL12XX=m
CONFIG_WL18XX=m
CONFIG_WLCORE_SPI=m
CONFIG_WLCORE_SDIO=m
[...]
CONFIG_MWIFIEX=m
CONFIG_MWIFIEX_SDIO=m
CONFIG_MWIFIEX_USB=m
```

So I compiled another custom_bbb system with the following config in `linux-4.4.43.defconfig`:
```
[...]
CONFIG_WL_TI=y
CONFIG_WL12XX=m
CONFIG_WL18XX=m
CONFIG_WLCORE_SPI=m
CONFIG_WLCORE_SDIO=m
CONFIG_MWIFIEX=m
CONFIG_MWIFIEX_SDIO=m
CONFIG_MWIFIEX_USB=m
[...]
```
But still I was unable to bring wlan up.

**Comment by cblock** [comment]
Then I booted the regular debian linux an bbgw: 

lsmod gives me: 
```
Module                  Size  Used by
ipt_REJECT              1638  2
nf_reject_ipv4          2858  1 ipt_REJECT
xt_TCPMSS               2983  1
xt_REDIRECT             1885  1
nf_nat_redirect         1790  1 xt_REDIRECT
xt_tcpudp               3091  6
xt_mark                 1285  5
iptable_mangle          1657  1
hci_uart               52789  0
btbcm                   7001  1 hci_uart
btqca                   7162  1 hci_uart
iptable_filter          1786  1
xt_conntrack            2955  2
ipt_MASQUERADE          1803  1
nf_nat_masquerade_ipv4     2867  1 ipt_MASQUERADE
iptable_nat             1997  1
nf_conntrack_ipv4      14735  3
nf_defrag_ipv4          1677  1 nf_conntrack_ipv4
nf_nat_ipv4             5392  1 iptable_nat
nf_nat                 15031  3 nf_nat_redirect,nf_nat_ipv4,nf_nat_masquerade_ipv4
nf_conntrack           98452  5 nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_ipv4
ip_tables              11896  3 iptable_filter,iptable_mangle,iptable_nat
x_tables               16523  10 xt_mark,ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_conntrack,iptable_filter,xt_TCPMSS,ipt_REJECT,xt_REDIRECT,iptable_mangle
bnep                   13652  2
bluetooth             419221  8 bnep,btbcm,btqca,hci_uart
arc4                    2019  2
wl18xx                 86482  0
wlcore                189892  1 wl18xx
mac80211              486884  2 wl18xx,wlcore
pruss_intc              3571  0
snd_soc_evm             5853  4
snd_soc_wilink8_bt      2266  1
pru_rproc              11359  0
omap_aes_driver        19045  0
omap_sham              21340  0
pruss                  11679  1 pru_rproc
snd_soc_davinci_mcasp    16653  2
snd_soc_edma            1290  1 snd_soc_davinci_mcasp
snd_soc_omap            3058  1 snd_soc_davinci_mcasp
omap_rng                4423  0
rng_core                7703  1 omap_rng
snd_soc_core          155549  5 snd_soc_davinci_mcasp,snd_soc_edma,snd_soc_omap,snd_soc_wilink8_bt,snd_soc_evm
snd_pcm_dmaengine       5209  2 snd_soc_core,snd_soc_omap
snd_pcm                83341  6 snd_soc_davinci_mcasp,snd_soc_core,snd_soc_omap,snd_pcm_dmaengine
snd_timer              19788  1 snd_pcm
snd                    59495  9 snd_soc_core,snd_timer,snd_pcm
wlcore_sdio             8077  0
usb_f_acm               7209  1
u_serial               11366  3 usb_f_acm
soundcore               7637  1 snd
usb_f_rndis            22191  1
g_multi                 5524  0
usb_f_mass_storage     42370  2 g_multi
u_ether                11898  2 usb_f_rndis,g_multi
libcomposite           43717  4 usb_f_acm,usb_f_rndis,g_multi,usb_f_mass_storage
evdev                  10695  1
cfg80211              418909  3 mac80211,wl18xx,wlcore
rfkill                 18276  6 cfg80211,bluetooth
uio_pdrv_genirq         3539  0
uio                     8822  1 uio_pdrv_genirq
```
So `wlcore` and `wl18xx` are loaded.

`dmesg -e | grep wl` yielded:
```
[  +2.116002] wlcore: wl18xx HW: 183x or 180x, PG 2.2 (ROM 0x11)
[  +0.237847] wlcore: loaded
[  +0.923645] wlcore: PHY firmware version: Rev 8.2.0.0.233
[  +0.400181] wlcore: firmware booted (Rev 8.9.0.1.55)
[  +0.218089] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[Apr 7 10:24] wlcore: down
```

And `ip link` shows all network interfaces just fine:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: usb0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether b0:d5:cc:71:ee:50 brd ff:ff:ff:ff:ff:ff
3: SoftAp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether b0:d5:cc:71:ee:5c brd ff:ff:ff:ff:ff:ff
4: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc mq state DOWN mode DORMANT group default qlen 1000
    link/ether 2c:f7:f1:06:25:d9 brd ff:ff:ff:ff:ff:ff
```

And now I'm stuck again... Any ideas what I missed out?

**Comment by fhunleth** [comment]
Did you try manually running `modprobe wl18xx` on the Nerves image to load the drivers?

**Comment by cblock** [comment]
Yes I did.  So here is the outboot, when booting my `custom_bbb` (current master with the aformentioned config changes):

```

U-Boot SPL 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15)
Trying to boot from MMC
bad magic


U-Boot 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15 -0500), Build: jenkins-github_Bootloader-Builder-351

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
Could not get PHY for cpsw: addr 0
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
reading /boot.scr
2308 bytes read in 14 ms (160.2 KiB/s)
## Executing script at 80000000
Running Nerves U-Boot script
reading uEnv.txt
** Unable to read file uEnv.txt **
reading zImage
3896096 bytes read in 272 ms (13.7 MiB/s)
reading am335x-bonegreen-wireless.dtb
55598 bytes read in 19 ms (2.8 MiB/s)
Kernel image @ 0x82000000 [ 0x000000 - 0x3b7320 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Device Tree to 8ffef000, end 8ffff92d ... OK

Starting kernel ...

[    0.000510] clocksource_probe: no matching clocksources found
[    0.357234] wkup_m3_ipc 44e11324.wkup_m3_ipc: could not get rproc handle
[    0.616380] omap_voltage_late_init: Voltage driver support not added
[    0.716546] bone_capemgr bone_capemgr: slot #0: No cape found
[    0.760905] bone_capemgr bone_capemgr: slot #1: No cape found
[    0.804548] bone_capemgr bone_capemgr: slot #2: No cape found
[    0.848533] bone_capemgr bone_capemgr: slot #3: No cape found
Erlang/OTP 19 [erts-8.3] [source] [async-threads:10] [kernel-poll:false]


00:00:03.805 [info]  Start Network Interface Worker
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C# modprobe wl18xx
#
```
`modprobe wl18xx`returns without an error. I interpret that as *ok* because specifying an invalid module yields:
```
modprobe MWIFIEX
modprobe: module MWIFIEX not found in modules.dep
```
The result of `lsmod` looks ok for me too:
```
# lsmod
    Not tainted
wl18xx 94147 0 - Live 0xbf1b0000
wlcore 216375 1 wl18xx, Live 0xbf169000
mac80211 558760 2 wl18xx,wlcore, Live 0xbf0b7000
cfg80211 560219 3 wl18xx,wlcore,mac80211, Live 0xbf000000
```
But `dmesg` does not contain any `wlcore` entries:
```
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 4.4.43 (root@cc2082bc23aa) (gcc version 5.3.0 (crosstool-NG v0.10.0) ) #1 SMP PREEMPT RT Fri Apr 7 10:58:03 UTC 2017
[    0.000000] CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: TI AM335x BeagleBone Green Wireless
[    0.000000] cma: Reserved 48 MiB at 0x9d000000
[    0.000000] Memory policy: Data cache writeback
[    0.000000] On node 0 totalpages: 131072
[    0.000000] free_area_init_node: node 0, pgdat c07c88c0, node_mem_map dcbe1000
[    0.000000]   Normal zone: 1024 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 131072 pages, LIFO batch:31
[    0.000000] CPU: All CPU(s) started in SVC mode.
[    0.000000] AM335X ES2.1 (sgx neon )
[    0.000000] PERCPU: Embedded 14 pages/cpu @dcba9000 s25120 r8192 d24032 u57344
[    0.000000] pcpu-alloc: s25120 r8192 d24032 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 130048
[    0.000000] Kernel command line: console=ttyO0,115200n8 quiet bone_capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIN root=/dev/mmcblk0p2 rootfstype=squashfs ro rootwait
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 461628K/524288K available (5212K kernel code, 352K rwdata, 2076K rodata, 348K init, 344K bss, 13508K reserved, 49152K cma-reserved, 0K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xe0800000 - 0xff800000   ( 496 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc07265cc   (7290 kB)
[    0.000000]       .init : 0xc0727000 - 0xc077e000   ( 348 kB)
[    0.000000]       .data : 0xc077e000 - 0xc07d6148   ( 353 kB)
[    0.000000]        .bss : 0xc07d9000 - 0xc082f33c   ( 345 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  RCU restricting CPUs from NR_CPUS=2 to nr_cpu_ids=1.
[    0.000000]  RCU kthread priority: 1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] IRQ: Found an INTC at 0xfa200000 (revision 5.0) with 128 interrupts
[    0.000000] OMAP clockevent source: timer2 at 24000000 Hz
[    0.000013] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
[    0.000025] clocksource: timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.000032] OMAP clocksource: timer1 at 24000000 Hz
[    0.000510] clocksource_probe: no matching clocksources found
[    0.000695] Console: colour dummy device 80x30
[    0.000842] WARNING: Your 'console=ttyO0' has been replaced by 'ttyS0'
[    0.000845] This ensures that you still see kernel messages. Please
[    0.000847] update your kernel commandline.
[    0.047109] Calibrating delay loop... 995.32 BogoMIPS (lpj=1990656)
[    0.047115] pid_max: default: 32768 minimum: 301
[    0.047252] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.047258] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.048048] CPU: Testing write buffer coherency: ok
[    0.048445] CPU0: thread -1, cpu 0, socket -1, mpidr 0
[    0.048585] Setting up static identity map for 0x80008280 - 0x800082e0
[    0.083248] Brought up 1 CPUs
[    0.083275] SMP: Total of 1 pro
```

`ip link` produces:
```
# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```
My gut feeling is that the driver is loaded but that I missed some config...

**Comment by fhunleth** [comment]
Hmm. I'm not sure. At this point, I might try to make to use the linux defconfig used by Debian. It will make a massive image, and then I'd manually load all of the drivers that Debian autoloaded. If that doesn't work, then that would rule out this being a Linux configuration issue. The other thing that I'd try is updating the Linux kernel to match the debian version's patch level. I suspect that has a low chance of helping, but I didn't look at the changes. I have a script in nerves_system_bbb to make a mega-patch out of the Debian Linux kernel changes for the BBB which would come in handy.

The main weird thing is that you aren't getting any messages from wlcore. I'd think that you'd at least see something. Another idea is to try adding a `printk` to http://elixir.free-electrons.com/source/drivers/net/wireless/ti/wlcore/spi.c?v=4.4.43#L329. Or at least, I think that's the function that should be called from a quick search of the kernel source. It could be that the hardware probe is failing. If it were me, I might try this first since it's a quick data point, but I'm not sure that I could tell you where to go from what you find without quite a few iterations.

I might have to get one myself. I have the feeling like you are really, really close, and that Nerves' trimmed down configuration is biting you.

**Comment by cblock** [comment]
Thanks for the hints and pointers, Frank. I'll try my best... I have to admit though, that editing the kernel is quite a bit from my comfort zone. Let's see how far I can get.

**Comment by fhunleth** [comment]
Thanks to a very generous member of the Nerves community, I received two BBGW's this evening. I made some progress and pushed my changes to the `bbgw` branch. Here's a log after `CTRL+C`'ing to a shell prompt:
```
# modprobe wl18xx
[    8.783623] cfg80211: World regulatory domain updated:
[    8.788822] cfg80211:  DFS Master region: unset
[    8.795762] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[    8.812288] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[    8.831388] cfg80211:   (2457000 KHz - 2482000 KHz @ 20000 KHz, 92000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[    8.848194] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[    8.869410] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[    8.883072] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[    8.900803] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[    8.918554] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[    8.926634] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
# modprobe wlcore-sdio
[   14.046625] wlcore: wl18xx HW: 183x or 180x, PG 2.2 (ROM 0x11)
[   14.059856] wlcore: loaded
# ifconfig wlan0 up
[   29.933323] wlcore: PHY firmware version: Rev 8.2.0.0.236
[   29.978329] wlcore: firmware booted (Rev 8.9.0.0.69)
# ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr DE:AD:BE:EF:00:00  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
There's at least one obvious issue left and that's setting the MAC address of the WiFi module. If you look above, it comes up as `DE:AD:BE:EF:00:00`. You might be able to associate with an access point at this point, but I'm not sure. The fix to this is in this [script](https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/jessie/debian/bb-wl18xx-wlan0).

I'm out of time right now and probably won't get a chance to make another pass until next week. However, if any of you get a chance to try out the branch or figure out how the MAC address programming shell script works, could you let me know?

**Comment by cblock** [comment]
Hi!
I tried your new branch, Frank and it works! Great!

 In particular I did the following:

- Compile a new custom_bbb based on your branch
- create a nerves 0.5.1. demo project and include httpoison as dependency
- boot bbgw
- execute the following
```
:os.cmd('modprobe wl18xx')
:os.cmd('modprobe wlcore-sdio')
Nerves.InterimWiFi.setup "wlan0", ssid: "xxx", key_mgmt: :"WPA-PSK", psk: "yyy"
```
Afterwards the bbgw registered in my local wlan and I was able to execute `HTTPoison.get("https://example.com/", [], [ ssl: [{:versions, [:'tlsv1.2']}] ])` which yielded a 200 response with the actual html page of example.com as body.

**Comment by fhunleth** [comment]
Thanks for verifying this. I'm going to spend some time on the BBGW shortly and try to wrap this up and make an official release.

**Comment by fhunleth** [comment]
The v0.12.0 release is now available with BBGW support. I'm keeping this issue open until we have a MAC address solution, but if you just have one BBGW on a WLAN, I think that you'll be fine.

**Comment by fhunleth** [comment]
Regarding the `DE:AD:BE:EF:00:00` MAC address, I have since learned that that is TI's way of letting you know that you're running the WiFi module uncalibrated. The official BBB scripts update the MAC address using other MAC addresses in the system (like one of the wired Ethernet MACs). Apparently if you zero out the MAC address in the calibration file (.nvs file), the WiFi module will use a MAC address programmed into it during manufacturing. Why the module is uncalibrated, I don't know, but apparently it works well enough uncalibrated for people to use it. The second thing that I don't understand is why the official BBB scripts don't zero out the MAC address so that the internal WiLink one is used. That seems so much easier.

**Comment by fhunleth** [comment]
See http://processors.wiki.ti.com/index.php/WL18xx_Writing_MAC_address for more information about the MAC address.

**Comment by fhunleth** [comment]
This set of code is intended to address the WL18xx MAC address issue: https://github.com/nerves-project/nerves_system_bbb/blob/e9b4f7bb57d885bae2c8f4289f81e18d529605e9/post-build.sh#L5-L31. I'm able to use the WiFi Module, but I'm not regularly using it, so I can't say whether there's an additional issue to be solved here. However, it seems good enough to close.
