### ISSUE TITLE
Firmware upgrades no longer seem to be working with v0.13.0

### ISSUE THREAD

**Issue by aadavids** [nerves-project/nerves_system_bbb#16]
Since updating nerves_system_bbb to v0.13.0, I'm no longer able to do firmware upgrades.

From a fresh nerves project after mix deps.get/mix firmware/etc:

1. Flash sd card with `mix firmware.burn`
BBB boots off this card into nerves successfully.

2. Update sd card with `mix firmware.burn --task upgrade`
BBB doesn't boot, just outputs `CCCCCCCC`

Here's the mix.lock for the project:
[mix.lock.bbb.txt](https://github.com/nerves-project/nerves_system_bbb/files/1149491/mix.lock.bbb.txt)

**Comment by aadavids** [comment]
`mix firmware.burn --task upgrade` seems to be working correctly: 
```
$ mix firmware.burn --task upgrade
Mix environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

Use 7.24 GiB memory card found at /dev/mmcblk0? [Yn] 
fwup: Upgrading the A partition
100%
Elapsed time: 1.044s
```

**Comment by aadavids** [comment]
`mix firmware.burn --task upgrade` seems to be working correctly: 
```
$ mix firmware.burn --task upgrade
Mix environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

Use 7.24 GiB memory card found at /dev/mmcblk0? [Yn] 
fwup: Upgrading the B partition
100%
Elapsed time: 1.044s
```

**Comment by fhunleth** [comment]
Fixed in 3d563b86b0636c34b143bfb0d03c8c692a3cc860.

Thanks for reporting this. I don't have a BBB with me right now, but I'm so certain this fixes the issue that I'm going to go ahead and close this as fixed. I'll test before the next official release, but if you get to it before then and it's still broke, please let me know.

**Comment by aadavids** [comment]
I just tested it, and it works. Thanks!

**Comment by fhunleth** [comment]
Great! Thanks for verifying!
