### ISSUE TITLE
add support for PRU's

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_bbb#26]
I don't have time to really get into this yet, but I want to document it somewhere...

I think a lot of users (including myself) want to begin using the PRU's with Nerves, but aside from some old ish stuff that @fhunleth did [here](https://github.com/fhunleth/troodon-cam) (this predates Nerves/Elixir), there is not much to be found.

I think we will need a number of things outside this repository also. Here's what I'd like to see...

* Buildroot support. This would *probably* require at least the following:
   * A device tree to be enabled.
   * the package `BR2_PACKAGE_AM335X_PRU_PACKAGE` to be enabled
      * This contains the assembler if i remember correctly.
* An Elixir API for access to the PRU's. This would have the following
   * assemble the PRU code
   * build a "loader" to load code into the PRU's.
   * Allow communication somehow if needed thru ElixirALE or similar.
* Docs for setting it all up and examples for usage.

Buildroot support would _probably_ be easy and could be enabled without breaking backwards compatibility (unless the DTBO, would break GPIO access...)

The second and third point there would _probably_ be  it's own repo, tho it could technically exist here..

I've been having a lot of discussions on Slack about this recently, and i would like to document it in a more followable manor.

**Comment by fhunleth** [comment]
FYI. I have PRU support enabled in the Linux kernel and device tree files. No change should be needed here unless there was a regression. If I remember right, I have both ways of loading the PRUs enabled. Someone should see what the tradeoffs between the ways are now. Only one way was available when I used it way back.

Regarding the assembler, the easier route w/ Nerves would be to run the assembler on the BBB as a preprocessing step to loading the PRUs. The problem with `BR2_PACKAGE_AM335X_PRU_PACKAGE` is that it has host side components and you can't package them in Nerves systems (well, you can, but then the assembler will only work on whatever platform you compile it on). I'd copy/paste the assembler source code into an Elixir PRU project. There aren't that many files. The downside of this is that it will be annoying to wait until runtime to find out that you have a syntax error in your PRU code. I can think of several ways to make this less annoying and you probably are aware of them too, but we might want to document how to iterate on PRU code changes so that people have a good experience.

**Comment by ConnorRigby** [comment]
Ah i should have looked to see if this repo had the PRU's enabled..

So What are the ways of enabling the PRUS's? Probably something with the "cape manager" (is it still called that?) I'm unaware of any other ways, besides maybe enabling the dtb at boottime?

**Comment by fhunleth** [comment]
The cape manager is still there, but it's for capes. The PRUs are enabled if the kernel module for them is loaded and they're defined in the device tree. Both of those things should be true. Just look at `dmesg`.

**Comment by ConnorRigby** [comment]
Okay. So one will either need to load a device tree, or a kernel module? Is interfacing them the same? And can either be done at runtime? Or does it need to happen at bootup?

**Comment by nuclearcanary** [comment]
I've been looking into enabling the PRUs. It looks like the excellent [beaglebone-universal-io](https://github.com/cdsteinkuehler/beaglebone-universal-io) already has provisions for enabling PRU access to the pins without extra `.dtb` files. So correct me if I'm wrong, but the only thing that would need to happen would be to add the compiled PRU binary to `/lib/firmware/am335x-pru0-fw` or `/lib/firmware/am335x-pru1-fw` using the `rootfs_overlay`. The bootloader would grab that binary and load it into the PRU.

**Comment by fhunleth** [comment]
@nuclearcanary The official Nerves image for the BBB ships with `config-pin` from the beaglebone-universal-io package. I vaguely recall having to tweak it slightly to work with Busybox's ash shell, but it should work for dynamically setting any pinmux needed for the PRU.

Also, regarding loading the PRU, I think that what you're saying is correct. There are two ways to do it. One is called UIO and that's the one that I used several years ago. The other way is remoteproc and that's what you're referring to. The thing that I really liked about UIO was that you could dynamically load PRU code and it made iterating really easy. I have to believe that the same is true for remoteproc, but the auto-load of PRU code from `/lib/firmware` makes me wonder.

One small correction, it's the Linux kernel that loads the PRU code and not the bootloader.

**Comment by nuclearcanary** [comment]
@fhunleth That makes sense. Thanks for the correction. I actually knew that from my research. It is the kernel module `pru_rproc` that loads the firmware.
From [this post](http://theduchy.ualr.edu/?p=996)
`rmmod -f pru_rproc` removes the module and disables the PRUs
`modprobe pru_rproc` loads the firmware(s) and boots the PRUs

Also, from [zeekhuge.me](https://www.zeekhuge.me/post/a_handfull_of_commands_and_scripts_to_get_started_with_beagleboneblack/), rebooting a PRU core reloads the firmware for that core.
`echo "4a334000.pru0" > /sys/bus/platform/drivers/pru-rproc/unbind` Shuts down core 0
`echo "4a334000.pru0" > /sys/bus/platform/drivers/pru-rproc/bind` Boots core 0, loading the new firmware

`echo "4a338000.pru1" > /sys/bus/platform/drivers/pru-rproc/unbind` Shuts down core 1
`echo "4a338000.pru1" > /sys/bus/platform/drivers/pru-rproc/bind` Boots core 1

His website only has a few posts, but they are very informative and easy to follow. I'm starting to wrap my head around these things. With the TI Code Generation Tools I should be able to cross compile and add them to the `rootfs_overlay` and get some lights blinking soon.

**Comment by fhunleth** [comment]
That's really useful information! I hope that it works.

**Comment by GregMefford** [comment]
@nuclearcanary By chance, are you trying to use PRUs to drive NeoPixels? It would be pretty neat if we could find a way to have https://github.com/GregMefford/nerves_neopixel work on both `rpi` and `bbb` with some target-specific options to swap out the low-level implementation.

**Comment by nuclearcanary** [comment]
Fantastic progress. Quick rundown of the sequence. Forked [nerves-system-bbb](https://github.com/nerves-project/nerves_system_bbb) and using the instructions to [customize your own nerves system](https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system). Verified I could produce and modify my own firmware. I installed the [PRU Code Generation Tools](http://software-dl.ti.com/codegen/non-esd/downloads/download.htm#PRU) and looked over the posts at [zeekhuge.me](https://www.zeekhuge.me/post/) to get a feel for what was happening. Cross compiled the [pru_blinky](https://github.com/ZeekHuge/BeagleScope/tree/port_to_4.4.12-ti-r31%2B/examples/firmware_exmples/pru_blinky) example. At first it wasn't working. I had to use a pin list to get the correct hex code for the gpio. Re-compiled, burned the firmware, booted the BBB, enabled it using `:os.cmd('config-pin P8_11 pruout')` from the console after loading the cape-universal using `:os.cmd('config-pin overlay cape-universal')`. **Presto!** The most complicated blinking light I have ever done. Then verified both methods listed above to halt/boot the PRUs. Dang, I'm going to have to start the blog I have been putting off just to remember how to do this. Now that I have it down, I can look into making it easier for other people. The easiest way I can think of is to have a set of pre-compiled PRU firmwares in the `rootfs_overlay` that can be loaded using Elixir. All it would have to do is enable PRU access for the pin(s), copy the firmware into place and boot the PRU(s). Communication could happen in one of several ways, C wrapper using DMA shared 8kB RAM, RPMsg, or other more brute force methods.  

@GregMefford I am not, but I can certainly look into it. I'm going to try and abstract as much of the PRU as I can. It might be reworking the wrapper to communicate with the PRU directly but surely it can be done.

Overall, I am pleased that it wasn't as hard as I feared. It looks like there is a path forward.

**Comment by elcritch** [comment]
Forking `nerves_system_bbb` and enabling the `ti-cgt-pru` buildroot package in the `nerves_defconfig` let me build the firmware for @nuclearcanary 's `pru_blinky` example without having to install any extra dependencies. That's super nice! The packages use TI's clpru which also handles the assembly. Not sure how people feel about relying on the TI's C/C++ compiler but it appears to work smoothly and the ability to use C/C++ on the PRU's makes them more approachable.

Unfortunately my changes are not merge-able currently as buildroot's 2017.11.1 version of the `ti-cgt-pru` package is broken (at least on my system it just hangs indefinitely). The current fix branch of buildroot 2017.11.x has updated/patched `ti-cgt-pru` package which works. Anyone know the "release" schedule for updating the buildroot version? Either that or merging in the patches to this package, though I'm not sure if/what the policy on that would be. 

P.S. shout out nuclearcanary for helping me understand the state of the pru's / nerves / and linux kmod's! @fhunleth thanks for merging in those kernel patches!

**Comment by elcritch** [comment]
As another note, I've been going through https://github.com/maciejjo/beaglebone-pru-dma and trying to figure out how to hook it up with some ADC projects I'm doing. It might be great to be able to use it to provide asynchronous Elixir/PRU messaging. :-) Just maybe...

**Comment by ConnorRigby** [comment]
I can confirm that `ti-cgt-pru` is broken in the current version of buildroot. Hangs forever.

**Comment by elcritch** [comment]
Thanks to @fhunleth there's a new `nerves_system_br` v0.17.0 which includes the patches for the fixed `ti-cgt-pru` from upstream buildroot. I just tested it with a new merge-able `nerves_system_bbb` branch with a fork of @nuclearcanary's `pru_blink` and it's all working!

**Comment by fhunleth** [comment]
Closing stale issue.
