### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by CaptChrisD** [nerves-project/nerves_system_bbb#350]
### Environment

* Elixir version (`elixir -v`):
```
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
```
* Nerves environment: (`mix nerves.env --info`)
```
mix hex.info nerves
Craft and deploy bulletproof embedded software

Config: {:nerves, "~> 1.11"}
Locked version: 1.11.1
```
* Additional information about your host, target hardware or environment that
  may help
  
  Building on MacOS 14.2.1

### Current behavior

The Ethernet port no longer works on latest version. This has been confirmed by Alex McLain as well and provided this report:
```
bbb 2.23.0 latest (br 1.28.1) - No network
bbb 2.22.0 (br 1.27.0) - No network
*bbb 2.21.0 (br 1.26.1) - No network
bbb 2.20.2 (br 1.25.3) - Network OK
```

Here is a gist of my log output: https://gist.github.com/CaptChrisD/17fc6398ad3a2166ad6fa5a619a47c2b. There is a suspicious line `SMSC LAN8710/LAN8720: probe of 4a101000.mdio:00 failed with error -5` but possibly other details in there to help troubleshoot.

We did a little troubleshooting and tried adding `CONFIG_MDIO_GPIO=y` on @fhunleth advice but this does not seem to have an impact.

### Expected behavior

The ethernet should work :)

**Comment by fhunleth** [comment]
I can't reproduce on either an original BeagleBone Black or a Seeed BeagleBone Green using a prebuilt CircuitsQuickstart image from https://github.com/elixir-circuits/circuits_quickstart/releases/tag/v0.11.0. 

What board are you using?

**Comment by CaptChrisD** [comment]
I tried on both Waveshare and Seeed Studio boards. All are newer board so latest revision (I believe RevC)

**Comment by fhunleth** [comment]
@CaptChrisD When you get a chance, could you validate that #351 works for you?

Here's a version that I built. After you download, just rename the file to remove the `.zip`. I add to add that for GitHub to be happy.

[circuits_quickstart-5.10.168.fw.zip](https://github.com/user-attachments/files/16808011/circuits_quickstart-5.10.168.fw.zip)

**Comment by CaptChrisD** [comment]
Yes! I installed both the fw file you sent and also built #351 and both seem to work as expected
