### ISSUE TITLE
Major version mismatch between host and target Erlang/OTP versions

### ISSUE THREAD

**Issue by bendiken** [nerves-project/nerves_system_bbb#4]
I updated my Nerves toolchains today to the latest releases, but the `bbb` target is giving me trouble.

This is on a system with `NERVES_SYSTEM_CACHE=local` set and in a project checkout after doing `rm -Rf deps _images rel/APPNAME` and `mix deps.unlock --all` to clean out any old dependencies:

    $ NERVES_TARGET=bbb mix do deps.get, deps.precompile
    * Updating nerves_lib (https://github.com/nerves-project/nerves_lib.git)
    * Updating nerves_networking (https://github.com/nerves-project/nerves_networking.git)
    Running dependency resolution
    Dependency resolution completed
      bbmustache: 1.0.4
      bunt: 0.1.6
      certifi: 0.4.0
      cf: 0.2.1
      credo: 0.4.8
      dialyxir: 0.3.5
      earmark: 1.0.1
      erlware_commons: 0.21.0
      ex_doc: 0.13.0
      excoveralls: 0.5.5
      exjsx: 3.2.0
      exrm: 1.0.8
      getopt: 0.8.2
      hackney: 1.6.1
      idna: 1.2.0
      jsx: 2.6.2
      metrics: 1.0.1
      mimerl: 1.0.2
      nerves: 0.3.4
      nerves_leds: 0.7.0
      nerves_ssdp_client: 0.1.3
      nerves_ssdp_server: 0.2.1
      nerves_system: 0.1.5
      nerves_system_bbb: 0.6.2
      nerves_system_br: 0.5.2
      nerves_toolchain: 0.6.3
      nerves_toolchain_arm_unknown_linux_gnueabihf: 0.6.1
      porcelain: 2.0.1
      providers: 1.6.0
      relx: 3.20.0
      ssl_verify_fun: 1.1.0
    ==> nerves_toolchain_arm_unknown_linux_gnueabihf
    [nerves_toolchain][compile]
    [nerves_toolchain][http] Toolchain up to date
    ==> nerves_system_bbb
    [nerves_system][compile]
    [nerves_system][local] Checking Cache for nerves_system_bbb-0.6.2
    [nerves_system][local] Found cached system
    ** (Nerves.Env.Exception) Major version mismatch between host and target Erlang/OTP versions
      Host version: 19
      Target version: 18

    This will likely cause Erlang code compiled for the target to fail in
    unexpected ways. Install an Erlang OTP release that matches the target
    version before continuing.

        (nerves_bootstrap) lib/mix/tasks/nerves.loadpaths.ex:20: Mix.Tasks.Nerves.Loadpaths.run/1
        (nerves_bootstrap) lib/mix/tasks/nerves.precompile.ex:19: Mix.Tasks.Nerves.Precompile.run/1
        (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
        (mix) lib/mix/task.ex:328: Mix.Task.run_alias/3
        (mix) lib/mix/task.ex:261: Mix.Task.run/2
        (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir) lib/enum.ex:651: Enum.each/2
        (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

The other targets I use (`rpi`, `rpi2`, `rpi3`, and `qemu_arm`) didn't give me any trouble executing the same command in the same project.

The host is OS X with Erlang 19.0.2, Elixir 1.3.2, etc, all installed from Homebrew as per the Nerves installation guide.

**Comment by fhunleth** [comment]
Due to a very confusing historical issue, the bbb is 0.1 ahead of the other platforms in its version numbering. What you really want is 0.7.2, but it's not quite published yet. If you use 0.7.1, you'll get something that works with the OTP numbering. I'd wait for 0.7.2, unless you're in a rush.

**Comment by bendiken** [comment]
The latest on Hex.pm would look to be 0.7.0: https://hex.pm/packages/nerves_system_bbb

To pull it in, I'm assuming I'd need to manually edit my `mix.lock`?

**Comment by fhunleth-lkc** [comment]
Sorry - I got the version numbers wrong in my haste to reply. 0.7.0 is the current version. 0.7.1 is building on ci.nerves-project.org. As soon as it completes I'll publish 0.7.1 to hex.

**Comment by fhunleth** [comment]
v0.7.1 is posted now on hex: https://hex.pm/packages/nerves_system_bbb
