### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_bbb#60]
We're going to be upgrading the Linux kernel soon. This may result in regressions. In order to prevent this, it would be good to have more tests. 

For example, I'm not using the PRUs. If PRU support is important to you, could you add a test that verifies that it works.

Here are some tests I've been adding for the RPi0: https://github.com/nerves-project/nerves_system_rpi0/commit/b790b1fe4878669191ee621089f2f106151ad7b3

**Comment by jjcarstens** [comment]
Closing this for now. If we want more tests, I think we need to discuss potential testing needs and make more specific issues for organizing the work
