### ISSUE TITLE
Question: Is this compatible with the BeagleBone Black Wireless?

### ISSUE THREAD

**Issue by Custodia** [nerves-project/nerves_system_bbb#74]
I'm a complete newcomer to the embedded world but I have been for a while now considered ordering a BeagleBone Black Wireless to setup some personal elixir project on. Before I do that though I would like confirmation that this works with the BeagleBone Black Wireless (it's not listed in the compatible systems) and how do you actually setup the wireless connection? Do the same instructions apply as for the BeagleBone Green Wireless?

**Comment by fhunleth** [comment]
I don't have a BeagleBone Black Wireless, but I've been told that someone got Nerves working on it.

A few notes:

1. The Beaglebones tend to be used for work projects and seem slower to get contributions back to the project than say our Raspberry Pi ports.
2. I have a major update staged for the Beaglebones to deal with a big change to something called a device tree overlay is handled. I hope to get it out in the next few days. There might be some hiccups.
3. There's an issue with setting MAC addresses on the WiFi module that's on the BBBW. I remember it being easy to workaround, but a fix was never submitted. Details are at #12. 

I'd try to persuade you to do your first project on a Raspberry Pi and then switch to a BBBW. However, I do appreciate that the BBB boards have some great features and I like how they support open source hardware. If you don't mind dealing with a few rough edges on the BBBW, then you'll be fine.

**Comment by Custodia** [comment]
Thanks a lot for taking the time to answer me!

In that case it sounds like I should start out fiddling with the raspberry pi instead (I already own one) and if I get really invested I will get the bbbw later.
