### ISSUE TITLE
BB green wireless fails to boot into nerves

### ISSUE THREAD

**Issue by cblock** [nerves-project/nerves_system_bbb#8]
Hi!

My SeeedStudio BeagleBone green wireless fails to boot into nerves from sd card due to not finding a valid device tree. To me it looks as if the patch at  [nerves_system_bbb/uboot/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch](am335x-bonegreen-wireless.dtb) sets fdtfile to `am335x-bonegreen-wireless.dtb` if it detects a bb green wireless. But fwup.conf is missing the corresponding file resource (a file resource for am335x-bonegreen.dtb is defined though in line 72).

So I guess that adding 

```
file-resource am335x-bonegreen-wireless.dtb {
    host-path = "${NERVES_SYSTEM}/images/am335x-bonegreen-wireless.dtb"
}  
```
to fwup.conf might fix the problem. I'm not sure though if the file itself has to be added somewhere.

For your reference: This is the boot log of my bb green wireless: 

```
U-Boot SPL 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15)
Trying to boot from MMC
bad magic


U-Boot 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15 -0500), Build: jenkins-github_Bootloader-Builder-351

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
Could not get PHY for cpsw: addr 0
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
reading /boot.scr
2308 bytes read in 14 ms (160.2 KiB/s)
## Executing script at 80000000
Running Nerves U-Boot script
reading uEnv.txt
** Unable to read file uEnv.txt **
reading zImage
4350536 bytes read in 304 ms (13.6 MiB/s)
reading am335x-bonegreen-wireless.dtb
** Unable to read file am335x-bonegreen-wireless.dtb **
Kernel image @ 0x82000000 [ 0x000000 - 0x426248 ]
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
Nerves boot failed!
SCRIPT FAILED: continuing...
Found U-Boot script /boot.scr
reading /boot.scr
2308 bytes read in 14 ms (160.2 KiB/s)
## Executing script at 80000000
Running Nerves U-Boot script
reading uEnv.txt
** Unable to read file uEnv.txt **
reading zImage
4350536 bytes read in 304 ms (13.6 MiB/s)
reading am335x-bonegreen-wireless.dtb
** Unable to read file am335x-bonegreen-wireless.dtb **
Kernel image @ 0x82000000 [ 0x000000 - 0x426248 ]
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
Nerves boot failed!
SCRIPT FAILED: continuing...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
gpio: pin 55 (gpio 55) value is 1
reading boot.scr
2308 bytes read in 14 ms (160.2 KiB/s)
Loaded script from boot.scr
gpio: pin 56 (gpio 56) value is 1
Running bootscript from mmc0:1 ...
## Executing script at 82000000
Running Nerves U-Boot script
reading uEnv.txt
** Unable to read file uEnv.txt **
reading zImage
4350536 bytes read in 301 ms (13.8 MiB/s)
reading am335x-bonegreen-wireless.dtb
** Unable to read file am335x-bonegreen-wireless.dtb **
Kernel image @ 0x82000000 [ 0x000000 - 0x426248 ]
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
Nerves boot failed!
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
Failed to mount ext2 filesystem...
** Unrecognized filesystem type **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
1185 bytes read in 15 ms (77.1 KiB/s)
Loaded environment from /boot/uEnv.txt
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.9-ti-r25 ...
7833256 bytes read in 444 ms (16.8 MiB/s)
loading /boot/dtbs/4.4.9-ti-r25/am335x-bonegreen-wireless.dtb ...
61860 bytes read in 46 ms (1.3 MiB/s)
loading /boot/initrd.img-4.4.9-ti-r25 ...
4777389 bytes read in 278 ms (16.4 MiB/s)
debug: [console=ttyO0,115200n8 quiet bone_capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIN root=UUID=532d64b4-5ee8-41ae-9a6e-f82b946e45ff ro rootfstype=ext4 rootwait coherent_pool=1M quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:48e5ad 0x88000000] ...
Kernel image @ 0x82000000 [ 0x000000 - 0x7786a8 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fb71000, end 8ffff5ad ... OK
   Loading Device Tree to 8fb5e000, end 8fb701a3 ... OK

Starting kernel ...

[    2.007515] wkup_m3_ipc 44e11324.wkup_m3_ipc: could not get rproc handle
[    2.153808] omap_voltage_late_init: Voltage driver support not added
[    2.161220] PM: Cannot get wkup_m3_ipc handle
[    2.277580] bone_capemgr bone_capemgr: slot #0: No cape found
[    2.321586] bone_capemgr bone_capemgr: slot #1: No cape found
[    2.365648] bone_capemgr bone_capemgr: slot #2: No cape found
[    2.409581] bone_capemgr bone_capemgr: slot #3: No cape found
Loading, please wait...
BOOT: recovering journal
BOOT: clean, 111922/238560 files, 515269/954112 blocks
[   11.591514]  remoteproc1: failed to load am335x-pru0-fw
[   11.732150]  remoteproc1: request_firmware failed: -2
[   11.737385] pru-rproc 4a334000.pru0: rproc_boot failed
[   12.251248]  remoteproc1: failed to load am335x-pru1-fw
[   12.273925]  remoteproc1: request_firmware failed: -2
[   12.279097] pru-rproc 4a338000.pru1: rproc_boot failed

Debian GNU/Linux 8 beaglebone ttyS0

BeagleBoard.org Debian Image 2016-05-27

Support/FAQ: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian

default username:password is [debian:temppwd]

The IP Address for usb0 is: 192.168.7.2
beaglebone login:
```

**Comment by fhunleth** [comment]
Your proposed change to the `fwup.conf` is on the right path. The other change that you'll need is to add `am335x-bonegreen-wireless` to https://github.com/nerves-project/nerves_system_bbb/blob/master/nerves_defconfig#L30.

Unfortunately, there's more if you're going to be using WiFi. The next change is to enable the wifi drivers for whatever wifi chip is on the BBGW. In Debian, you can figure it out with `lsmod` and enable the same wifi module in the Linux config (https://github.com/nerves-project/nerves_system_bbb/blob/master/linux/linux-4.4.43.defconfig).

I don't have a BBGW, so I'm not sure if anything else needs to be updated, but I don't think so.

**Comment by cblock** [comment]
Thanks for the hints. I only had to update the two places you mentioned: https://github.com/cblock/nerves_system_bbb/commit/de4d31d1b792288a2622cdee6930bdb018dee480

Afterwards I was able to the the hello_wifi demo project up and running including a connection to my wifi.

BBGW uses wl18xx chipset, which is configured through the `0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch` patch already.  

Do you want me to send you a PR for these changes?

**Comment by fhunleth** [comment]
Yes - please send a PR. I'm sure that we'll have more BBGW users and they'll appreciate your updates.

Thanks!

**Comment by cblock** [comment]
Ok done: PR https://github.com/nerves-project/nerves_system_bbb/pull/10

**Comment by cblock** [comment]
Frank, sorry to reopen this issue. I just tried the new release and unfortunately `am335x-bonegreen-wireless.dtb` is not generated / included. Thus boot fails. Obviously I have missed something. Do you have any idea what I have to adjust in order to properly generate `am335x-bonegreen-wireless.dtb` during the release process?

**Comment by fhunleth** [comment]
Sorry, somehow I missed the notification with your new comments. I'm pretty sure that I fixed the issue in ba7bbd496e9e5f437e9e42c55301905728bc4bc0. Could you update and try?

**Comment by fhunleth** [comment]
I think that the problem is a missing wifi driver. Earlier you mentioned that you had wifi work, so I got a little confused, but assumed that you enabled the wifi driver locally. Normally it's a two step process of enabling the wifi driver in the Linux kernel and enabling the wifi driver's firmware in the Buildroot linux-firmware package. If you've already done all this, then my next guess would be that the wifi driver needs to be manually loaded. You can do this via `:os.cmd('modprobe xyzdriver')` in your main application (or try it out at the IEx prompt) or put the driver's name in the `kernel_modules` section of your `mix.exs` if you're using `bootloader`. (I'm not using `bootloader` yet, so I'd be doing the former, but I noticed the `kernel_modules` section in the `mix.exs`.)

**Comment by brucepom** [comment]
Hi cblock,

I've run into the same issue as you. `Undefined applications: [nerves]`. I probably missed whatever you missed. I've run into it with other Nerves systems too, I don't think it's specific to BBB. I've always solved it by making the following change in my application's `mix.exs` (note this is in the application, not the system).
Find `{:nerves, "~> 0.5.0", runtime: false}` and remove `runtime: false` (or change it to `true`).

**Comment by brucepom** [comment]
Thanks for your work on this guys. I've just tested on BBGW. I followed the steps for [Customizing Your Own Nerves System](https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system). I didn't make any changes to the current bbb system except to rename it and remove the set `artifact_url` in `nerves.exe` to an empty list. The system built and booted the Elixir app without problems on BBGW. I haven't tested the built-in wifi yet.

**Comment by cblock** [comment]
...so for me it doesn't work somehow. But maybe it's just a screwed up local dev environment. If it works for you @brucepom I suggest having a new release (or at least a release candidate). I'll then try out the new version.

**Comment by fhunleth** [comment]
@brucepom, @cblock, I'll create a new nerves_system_bbb release. That will make it work out of the box without needing to create a custom system. Would it be possible, though, for one of you to load Debian on the board and see which wifi driver gets loaded? If you're not sure, posting the output of `lsmod` and `dmesg` should be sufficient for me to figure it out.

Regarding your post above, `:runtime` should be `false`, but maybe @mobileoverlord has an idea of why you need it to be `true`.

**Comment by cblock** [comment]
@fhunleth thanks a lot. The wifi driver is `wl18x`. Attached please find the [lsmod](https://gist.github.com/cblock/76e2208c10703a43ebfe3c764f76305e) and [dmesg](https://gist.github.com/cblock/f5399d66733d19fb3cf5770129cf882e) output of my bbb wireless.

As I see it the wl18x driver is already configured through the `linux/rcn-linux-4.4.43-ti.patch` and `linux/rcn-linux-4.4.9-ti.patch`.

**Comment by GregMefford** [comment]
I suspect that the systems are trying to pull `nerves` in as a run-time dependency because this isn't marked as `runtime: false`: https://github.com/nerves-project/nerves_system_bbb/blob/master/mix.exs#L24

**Comment by brucepom** [comment]
I know what you mean @GregMefford. I tried setting `runtime: false` in my custom system's `mix.exs` but that didn't resolve the error for me. I only get the error when I try to use a custom system, so I think you're on the right track. I haven't added an issue for this as I assumed it's quite likely something specific to my setup and there was an easy workaround for me. I'm sure we'll hear about it more if others are running into it.

**Comment by cblock** [comment]
@GregMefford @brucepom I can confirm that adding `runtime: false` to the nerves dependency doesn't have an effect. I still get the `==> Release failed, during .boot generation: Undefined applications: [nerves]` error.

**Comment by brucepom** [comment]
Hey @cblock, good to know, just to clarify my experience:
1. Adding `runtime: false` to the nerves dependancy in my custom **system** did not resolve the error.
2. Removing `runtime: false` (or changing it to true) in my nerves **app** did resolve the error.

**Comment by cblock** [comment]
I just uploaded both as git repositories: 
- [custom_bbb](https://github.com/cblock/custom_bbb) my custom system
- [bbb_test](https://github.com/cblock/bbb_test) -> Plain 0.5.0 nerves app without any customization other than that required to pull in custom_bbb

I remove .gitignore file from both repos so that you can inspect all generated `.nerves`, `deps`, and `_build` artefacts including [build.log](https://github.com/cblock/custom_bbb/build.log)

@brucepom to answer your question: In my [nerves sample app](https://github.com/cblock/bbb_test) [I've set the nerves dependency](https://github.com/cblock/bbb_test/blob/master/mix.exs#L51) to `runtime: false`.

**Comment by cblock** [comment]
...just had another idea: 
As understand it the `deps` method in `mix.exs` pattern matches on the `@target` variable.

The [docs](https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system) advise to add a new method 
```
def deps("custom_rpi3") do
  [{:custom_rpi3, path: "/path/to/your/custom_rpi3"}]
end
```
and to `export MIX_TARGET=custom_rpi3` before calling mix firmware.
But the generated mix.exs contains a `deps` method that also defines `nerves_runtime` as dependency: 

```
def deps(target) do
    [{:nerves_runtime, "~> 0.1.0"},
     {:"nerves_system_#{target}", "~> 0.11.0", runtime: false}]
  end 
```

That basically means that nerves_runtime is not required for my `custom_xxx` build target, right? Maybe that's the problem? I'll try to figure that out tomorrow.

**Comment by brucepom** [comment]
Hey @cblock, just to clarify, I resolved the issue by setting the `runtime: **true**` in my nerves app, not false as you mentioned above.

**Comment by cblock** [comment]
@brucepom thanks a lot. The error was basically sitting in front of the laptop. :)
Now it works! Great! I get an iex shell on my bbg wireless.

For future reference: This is the relevant part of my `mix.exs` file:

```
def deps do
    [{:nerves, "~> 0.5.0", runtime: true}] ++
    deps(@target)
  end

  # Specify target specific dependencies
  def deps("host"), do: []
  def deps("custom_bbb") do
    [
      {:nerves_runtime, "~> 0.1.0"},
      {:custom_bbb, path: "/Users/carsten/ElixirProjects/custom_bbb"}
    ]
  end
  def deps(_target) do
    [
      {:nerves_runtime, "~> 0.1.0"},
    ]
  end
```

**Comment by brucepom** [comment]
Sweet! Glad it's working (:

**Comment by fhunleth** [comment]
I made some untested updates in the bbgw branch (https://github.com/nerves-project/nerves_system_bbb/tree/bbgw) to support the TI WiLink8. It's late, but hopefully, I got the right driver and wireless module firmware enabled. If you're able to try this out, run `:os.cmd('modprobe wl18xx')` early on to load the wireless driver.

Also, I marked the `:nerves` dependency as `runtime: false`. It really doesn't have any runtime code, so it really should be marked this way everywhere. We're getting used to `runtime: false`, so it hasn't propagated. @GregMefford - could you check my `mix.exs` and deps changes? I know Justin is busy this week with work and EEF. If they're good, we should make all of the systems this way. I'm actually surprised that we haven't heard about this on other platforms.

**Comment by GregMefford** [comment]
@fhunleth Yes, that looks right to me. I agree that they're all broken but it doesn't seem to cause a problem except for custom systems. I think we haven't heard about it from many people yet because people with custom systems are less likely to hop onto the latest version immediately, so they probably haven't hit the problem yet.

@cblock Good catch on the docs about adding a custom `deps` function head. I agree that we should advise people to include `nerves_runtime` in there in addition to their custom system (`custom_rpi3` in the example). For now, it isn't really a big deal because there's not much in `nerves_runtime` for this release, but it'll matter more in the future.

**Comment by GregMefford** [comment]
@cblock Also, your `dep deps(_target)` definition is probably not what you want because it doesn't actually include a system dependency. For example, if you did `MIX_TARGET=rpi3`, you'd end up with a build that would try to run on your host except it would have `nerves_runtime` included. If you want to support any of the official Nerves systems, we recommend you use this:

```elixir
def deps(target) do
  [{:"nerves_system_#{target}", ">= 0.0.0"}]
end
```

**Comment by cblock** [comment]
@GregMefford thanks for your advice concerning the regular deps method. I updated my mix.exs accordingly

@fhunleth I just tried building a custom system using your bbgw branch together with interim_wifi 0.2.0.
 
First of all the nerves dependency error is gone. I can boot the bbgw with the custom firmware but I get the following error during startup: `init terminating in do_boot (cannot expand $ERTS_LIB_DIR in bootfile)`

**Comment by cblock** [comment]
Update: setting `MIX_ENV=prod` resolved the error above. Interestingly it then boots into eshell.

@fhunleth executing `:os.cmd('modprobe wl18xx')` yields nothing no error and no other log output / response code

**Comment by fhunleth** [comment]
@mobileoverlord If you're around, that `ERTS_LIB_DIR` error sounds really familiar.

@cblock Hmm. I'm struggling with how to debug this remotely. Do you are does anyone else with a BBGW have a way of letting me log in and poke around?

**Comment by GregMefford** [comment]
I think the fix for the missing `ERTS_LIB_DIR` is that you need to run `mix nerves.release.init` if you didn't do it during project creation, or it failed to do it automatically for some reason.

**Comment by cblock** [comment]
@fhunleth and @GregMefford thanks for all your effort. I really appreciate this!

The error was in front of the laptop (again!): `rel/config.exs` was indeed missing. And so I generated one running `mix release.init`. That basically creates a config.exs so I thought all is fine. Next nerves complained about `ERTS_LIB_DIR`. I then changed in that `config.exs` the `set include_erts: false`to `true`, which finally lead to the bbb booting but into eshell and not into iex. I'll see if I can help others avoid this trap in future by adding a short FAQ to the nerves docs.

@fhunleth this is the output from `:os.cmd('modprobe wl18xx')` 

```
iex(1)> :os.cmd('modprobe wl18xx')
[]
iex(2)> {:uevent, "add@/module/cfg80211",
 %{action: "add", devpath: "/module/cfg80211", seqnum: "712",
   subsystem: "module"}}
{:uevent, "add@/class/ieee80211",
 %{action: "add", devpath: "/class/ieee80211", seqnum: "713",
   subsystem: "class"}}
{:uevent, "add@/devices/platform/regulatory.0",
 %{action: "add", devpath: "/devices/platform/regulatory.0",
   modalias: "platform:regulatory", seqnum: "714", subsystem: "platform"}}
{:uevent, "add@/module/mac80211",
 %{action: "add", devpath: "/module/mac80211", seqnum: "715",
   subsystem: "module"}}
{:uevent, "add@/module/wlcore",
 %{action: "add", devpath: "/module/wlcore", seqnum: "716",
   subsystem: "module"}}
{:uevent, "add@/module/wl18xx",
 %{action: "add", devpath: "/module/wl18xx", seqnum: "717",
   subsystem: "module"}}
{:uevent, "add@/bus/platform/drivers/wl18xx_driver",
 %{action: "add", devpath: "/bus/platform/drivers/wl18xx_driver", seqnum: "718",
   subsystem: "drivers"}}

nil
```

Also initializing the interim wifi seems to work: 

```
{ok, pid} = Nerves.InterimWiFi.setup "wlan0", ssid: "xxx", key_mgmt: :"WPA-PSK", psk: "yyy"

00:03:06.390 [debug] Elixir.Nerves.InterimWiFi setup(wlan0, [ssid: "RidersToTheSea", key_mgmt: :"WPA-PSK", psk: "Neubergweg1a"])

00:03:06.408 [info]  WiFiManager(wlan0) starting

00:03:06.409 [info]  Register Nerves.NetworkInterface "wlan0"
{:ok, #PID<0.100.0>}

00:03:06.425 [info]  Done Registering
```
If you need help documenting and / or further testing the changes let me know. I'm happy to support you.

**Comment by fhunleth** [comment]
Super!!!!

I'll merge the changes with `master` and put on the todo list to make a new official release for BBB. One thing that I wasn't sure about was did you end with `include_erts: true` or `false`? ERTS shouldn't be in the release, but the system libs should be.

And one last thing, any docs, hints, or help that you can contribute for making BBGW support easier for others would be fantastic. Thank you so much for hanging in there and seeing this through!

**Comment by cblock** [comment]
...the default `config.exs` generated by `mix nerves.release.init` works for me (see below). As I don't set `ERL_LIB_DIR` as environment variable I assume that `include_erts` is false.

```
use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: :dev

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set cookie: :"@)xM43,^/4]&&Wv$Bf`=VhCMqt!5H:;Z>CF%;L7>gH^{UJdh17)q:G6u)v2k)XL]"
end

environment :prod do
  set cookie: :"@)xM43,^/4]&&Wv$Bf`=VhCMqt!5H:;Z>CF%;L7>gH^{UJdh17)q:G6u)v2k)XL]"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :bbb_test do
  set version: current_version(:bbb_test)
  if System.get_env("NERVES_SYSTEM") do
    set dev_mode: false
    set include_src: false
    set include_erts: System.get_env("ERL_LIB_DIR")
    set include_system_libs: System.get_env("ERL_SYSTEM_LIB_DIR")
    set vm_args: "rel/vm.args"
  end
end
```

**Comment by fhunleth** [comment]
Great! The default does the right thing.

**Comment by brucepom** [comment]
Thanks everybody. @cblock I'm interested to hear if you tried out the connection, for example did you see if you were able to connect to the internet from your bbgw?

I'm getting the same results as you reported when running `:os.cmd('modprobe wl18xx')` and `{ok, pid} = Nerves.InterimWiFi.setup "wlan0", ssid: "xxx", key_mgmt: :"WPA-PSK", psk: "yyy"`. But I don't think I'm actually successfully connecting to my wlan.

After calling `Nerves.InterimWiFi.setup` I get the same output as you (ends with `[info]  Done Registering`) but that's all I get, I'd expect to get a lot more output from InterimWifi and probably expect to see something like `WiFiManager.EventHandler(wlan0) wifi_connected` if it had actually connected. I tried a couple of other things to see if I had a network connection:
Check if interface exists:
```
iex(4)> Nerves.NetworkInterface.interfaces
["lo"] # Note no wlan0 listed
```
Check for internet connectivity:
```
iex(5)> :httpc.request(:get, {'http://www.erlang.org', []}, [], [])
{:error,
 {:failed_connect,
  [{:to_address, {'www.erlang.org', 80}}, {:inet, [:inet], :nxdomain}]}}
```

**Comment by cblock** [comment]
Hi @brucepom and @fhunleth !

Thanks for your response and sorry for my belated reply. I just walked through the whole procedure of creating a custom bbb system again using the latest master version of this repo and the latest nerves version (0.5.1). I can now confirm what you found @brucepom : Only "lo" network interface is registered. Also my wlan router does  show a new device being registered. So there's something still missing. I suggest we open a new ticket for this. @brucepom would you ming going ahead?

**Comment by brucepom** [comment]
Thanks @cblock, I created a new issue here: https://github.com/nerves-project/nerves_system_bbb/issues/12
